version: 2.1

orbs:
  jq: circleci/jq@2.2.0
  aws-cli: circleci/aws-cli@3.1.4

executors:
  app-executor:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/repo
  
  terraform-executor: 
    docker:
      - image: hashicorp/terraform:latest

commands:
  aws-oidc-setup:
    description: Setup AWS auth using OIDC token
    parameters:
      aws-role-arn:
        type: string
    steps:
      - run:
          name: Get short-term credentials
          command: |
            STS=($(aws sts assume-role-with-web-identity --role-arn << parameters.aws-role-arn >> --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds 900 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
            echo "export AWS_ACCESS_KEY_ID=${STS[0]}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${STS[1]}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${STS[2]}" >> $BASH_ENV
      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity

aliases:
  - &show-current-branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  
  - &install-dependencies
    run:
      name: Install Dependencies
      command: |
        mkdir -p artifacts

jobs:
  testconnection:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-oidc-setup:
          aws-role-arn: ${AWS_ROLE_ARN}
      - run:
          name: Test AWS connection
          command: aws s3 ls

  setup:
   executor: app-executor
   steps:
      - checkout
      - *show-current-branch
      - *install-dependencies
      - run:
          name: Copy Terraform folder for EKS module
          command: cp -r eks artifacts/eks/
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  terraform-validate:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch
      -  run:
          name: Code Quality
          command: |
             cd eks/
             terraform init -backend=false
             terraform validate
             terraform fmt -check

workflows:
  aws-cli:
    jobs:
      - testconnection:
          context: calvine-cloudonmymind

      - setup:
          requires:
            - testconnection

      - terraform-validate:
          context: calvine-cloudonmymind
          requires:
            - setup
          # filters:
          #   branches:
          #     only:
          #       - main
